version: '3.8'

services:
  php:
    volumes:
      - ./:/var/www/html:cached
    environment:
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
    ports:
      - "9009:9003"

  mysql:
    ports:
      - "3327:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev_root_password
    volumes:
      - mysql_dev_data:/var/lib/mysql

  nginx:
    ports:
      - "8028:80"


###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

volumes:
  mysql_dev_data: